set_property SRC_FILE_INFO {cfile:C:/Users/Admin/Desktop/TH_TKMTHS/GCD/sqrt/sqrt.srcs/constrs_1/imports/SQRT/timing_constraint_sqrt.xdc rfile:../../../sqrt.srcs/constrs_1/imports/SQRT/timing_constraint_sqrt.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R3 [get_ports {SYSCLK_P}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P3 [get_ports {SYSCLK_N}]
